<?php

namespace Lost\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceLocationDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLocationDiscountRepository extends EntityRepository
{
    public function getRemoveDiscountList($serviceLocationId,$NotInIds){
        
        $qb = $this->createQueryBuilder('sd')
        ->select('sd')
        ->where('sd.id NOT IN(:Id)')
        ->setParameter('Id', $NotInIds)
        ->andWhere('sd.serviceLocation = :serviceLocation')
        ->setParameter('serviceLocation', $serviceLocationId);
    
        $delDiscount = $qb->getQuery()->getResult();
    
        if($delDiscount){
    
            return $delDiscount;
        }
    
        return false;
    }
}
