<?php

namespace Lost\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {
    
    public function getAllCountrywiseService() {

        $query = $this->createQueryBuilder('c')
                      ->innerJoin('c.countrywiseService', 'cy');

        return $query;
    }
    
    public function getAllCountrywiseServiceSearch($query, $search) {

        $query->innerJoin('cy.services', 's')
              ->where('c.name LIKE :cname OR s.name LIKE :cname ')
              ->setParameter('cname', '%'.$search.'%');
       
        return $query;
    }

    public function getCreditCardCountry() {
    
        $query = $this->createQueryBuilder('c')
                ->orderBy('c.name','ASC');
        $result = $query->getQuery()->getResult();
        
        $country = array();
        if($result){

            foreach ($result as $val){
                
                $country[$val->getIsoCode()] = $val->getName();
            }
        }        
        
        return $country;
    }
}
