<?php

namespace Lost\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository {
    
    public function getAllServices() {

        $query = $this->createQueryBuilder('s')
                ->select('s.id, s.name, s.status');

        return $query;
    }
    
    public function getAllServicesSearch($query, $search) {

        $query->where('s.name LIKE :sname')
            ->setParameter('sname', '%'.$search.'%');
       
        return $query;
    }
    
}
