<?php

namespace Lost\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * UserActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityLogRepository extends EntityRepository {

    public function getAllActivityLogs() {

        $query = $this->createQueryBuilder('al')
                ->orderBy('al.id', 'desc');

        return $query;
    }

    public function getActivityLogSearch($query, $searchParam) {

        if (isset($searchParam['activity']) && $searchParam['activity']) {
            $query->where('al.activity = :activity')
                    ->setParameter('activity', $searchParam['activity']);
        }
 
        if (isset($searchParam['user']) && $searchParam['user']) {
            $query->andWhere('al.user LIKE :user')
                    ->setParameter('user', '%'. trim($searchParam['user']) . '%');
                    //->andWhere('u.roles LIKE :userRole')
                    //->setParameter('userRole', '%ROLE_USER%');
        }
        
        if (isset($searchParam['admin']) && $searchParam['admin']) {
            $query->andWhere('al.admin LIKE :admin')
                    ->setParameter('admin', '%'. trim($searchParam['admin']) . '%');
                    //->andWhere('a.roles NOT LIKE :adminRole')
                    //->setParameter('adminRole', '%ROLE_USER%');
        }

        if (isset($searchParam['ip']) && $searchParam['ip']) {
            $query->andWhere('al.ip LIKE :ip')
                    ->setParameter('ip', '%' . trim($searchParam['ip']) . '%');
        }

        if (isset($searchParam['sessionId']) && $searchParam['sessionId']) {
            $query->andWhere('al.sessionId = :sessionId')
                    ->setParameter('sessionId', $searchParam['sessionId']);
        }

        if (isset($searchParam['startDate']) && $searchParam['startDate'] != '' && isset($searchParam['endDate']) && $searchParam['endDate'] != '') {

            $query->andWhere('al.timestamp >= :startDate')
                    ->setParameter("startDate", $searchParam['startDate']->format('Y-m-d'));
            $query->andWhere('al.timestamp <= :endDate')
                    ->setParameter("endDate", $searchParam['endDate']->format('Y-m-d 23:59:59'));
        }

        return $query;
    }

}
