<?php

namespace Lost\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCreditRepository extends EntityRepository
{
     public function getAllCredit() {    
        $query = $this->createQueryBuilder('uc')
        ->select('uc')
        ->orderBy('uc.id', 'desc');
        return $query;
    }
    
  
    
    public function getCreditSearch($query, $searchParam) {
        
        if ($searchParam['credit']) {
            $query->andWhere('uc.credit LIKE :credit')
            ->setParameter('credit', '%'. trim($searchParam['credit']) . '%');
             
        }
         if ($searchParam['amount']) {
            $query->andWhere('uc.amount LIKE :amount')
            ->setParameter('amount', '%'. trim($searchParam['amount']) . '%');
             
        }
      
        return $query;
    }
    
}
