<?php

namespace Lost\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserMacAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMacAddressRepository extends EntityRepository
{
}
