lost_service_homepage:
    path:     /hello/{name}
    defaults: { _controller: LostServiceBundle:Default:index }

lost_service_addcart:
    path:     /plan/addcart
    defaults: { _controller: LostServiceBundle:Service:addCart}

lost_service_purchaseverification:
    path:     /service/purchaseverification
    defaults: { _controller: LostServiceBundle:Service:purchaseverification}

lost_service_plan:
    path:     /package/{service}/{addon}
    defaults: { _controller: LostServiceBundle:Service:package, service:null, addon:null}

lost_service_paymentcancel:
    path:     /service/paymentcancel/{id}
    defaults: { _controller: LostServiceBundle:Service:paymentCancel, id:null }
    
lost_service_paymentconfirm:
    path:     /paypal/paymentconfirm
    defaults: { _controller: LostServiceBundle:Paypal:paymentconfirm }
    
lost_service_purchase_order_confirm:
    path:     /purchase-order-comfirmation
    defaults: { _controller: LostServiceBundle:Service:orderComfirmation } 
           
lost_service_channel_list:
    path:     /service/channel-list/{packageId}
    defaults: { _controller: LostServiceBundle:Service:channelList }

lost_service_premium_channel_list:
    path:     /service/premium-channel-list/{packageId}
    defaults: { _controller: LostServiceBundle:Service:premiumChannelList }

lost_service_active_by_credit:
    path:     /service/proceed-activation
    defaults: { _controller: LostServiceBundle:Service:activeServiceByCredit }    
    
    
lost_payment_process_confirm_detail:
    path:     /confirm-payment-detail/{step}
    defaults: { _controller: LostServiceBundle:ConfirmOrder:confirmPaymentDetail,step:null }        

lost_do_payment_process:
    path:     /do-payment-process
    defaults: { _controller: LostServiceBundle:ConfirmOrder:doPaymentProcess }
    
lost_paymentby_dodirect:
    path:     /dodirect-process
    defaults: { _controller: LostServiceBundle:Paypal:dodirectProcess }

lost_paymentby_expresscheckout:
    path:     /service/paypalexpresscheckout
    defaults: { _controller: LostServiceBundle:Paypal:paypalexpresscheckout }
    
lost_paymentby_milstar:
    path:     /milstar-payment
    defaults: { _controller: LostServiceBundle:MilstarPayment:milstarProcess }

lost_process_payment_option:
    path:     /payment/{paymentby}
    defaults: { _controller: LostServiceBundle:Service:processPaymentOption, paymentby:null}

 
  
lost_package_select:
    path:     /package-select/{service}
    defaults: { _controller: LostServiceBundle:Service:packageSelect, service:null}
    
lost_service_remove:
    path:     /service-remove/{service}
    defaults: { _controller: LostServiceBundle:Service:serviceRemove, service:null}
    



    
    