<?php

namespace Lost\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MilstarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilstarRepository extends EntityRepository
{
}
