<?php

namespace Lost\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends EntityRepository
{
    // get support category
    public function getAllPackages() {
    
        $qb = $this->createQueryBuilder('p');
    
        return $qb;
    }
    
    // get support category using searching
    public function getPackagesSearch($query, $searchParam) {
    
        if (isset($searchParam['name']) && !empty($searchParam['name'])) {
    
            $query->where('p.name LIKE :search')
            ->setParameter('search', '%'. trim($searchParam['name']) . '%');
        }
    
        return $query;
    }
    
    public function getPackages($user){
        
        $db = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.status =:status')
                    ->setParameter('status', 1);
        
        if($user->getActivePackageIds()){
            $db->andWhere('p.packageId NOT IN(:packageId)');
            $db->setParameter('packageId', $user->getActivePackageIds());
        }
        
        $query = $db->getQuery();
                
        $result = $query->getResult();
                
        return $result;
    }
}
